name: Build SCADA-IDS-KC Standalone (No Bundled Npcap)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-without-npcap:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build standalone executable
        run: |
          echo "Building standalone executable..."
          cd packaging
          pyinstaller --clean SCADA-IDS-KC-main.spec

      - name: Create release package
        run: |
          echo "Creating release package..."
          New-Item -ItemType Directory -Path "release" -Force
          Copy-Item "packaging/dist/*" "release/" -Recurse -Force
          echo "SCADA-IDS-KC Standalone - Built $(Get-Date)" > "release/BUILD_INFO.txt"

      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if (Test-Path "release/SCADA-IDS-KC.exe") {
            $exe = Get-Item "release/SCADA-IDS-KC.exe"
            echo "✅ Executable built successfully: $($exe.Length) bytes"
          } else {
            echo "❌ Executable not found!"
            Get-ChildItem release -ErrorAction SilentlyContinue
            exit 1
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scada-ids-kc-standalone
          path: release/
          retention-days: 30
