name: Build SCADA-IDS-KC with Bundled Npcap

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  NPCAP_VERSION: "1.82"

jobs:
  build-with-npcap:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller requests

      - name: Prepare Npcap installer
        run: |
          echo "Preparing Npcap installer..."
          python scripts/prepare_npcap.py --version ${{ env.NPCAP_VERSION }} --verbose

      - name: Build executable with bundled Npcap
        run: |
          echo "Building executable with bundled Npcap..."
          cd packaging
          pyinstaller --clean SCADA-IDS-KC-main.spec

      - name: Create release package
        run: |
          echo "Creating release package..."
          New-Item -ItemType Directory -Path "release" -Force
          Copy-Item "packaging/dist/*" "release/" -Recurse -Force
          echo "SCADA-IDS-KC with Bundled Npcap - Built $(Get-Date)" > "release/BUILD_INFO.txt"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scada-ids-kc-with-npcap
          path: release/
          retention-days: 30
